GPU Usage(Gbyte): 0.6714949607849121
backbone: resnet18
backward(min): 3.8729999999999998
batch_size: 256
checkpoint_dir: experiment_checkpoints/
dataset_dir: D:/Datasets/cifar10/train/
device: cuda
drop_last: true
experiment: Magic_cube
forward(min): 7.735833333333333
input_size: 32
log_dir: experiment_checkpoints/Magic_cube\Base_mdDCL_VMmean_n_ep50_v4
loss_func: DCL
max_epochs: 50
memory_bank_size: 4096
model: DCL
momentum: false
name: Base_mdDCL_VMmean_n_ep50_v4
num_workers: 6
optimizer: SGD
path_to_data_Alex_clothing: D:/Datasets/clothing
path_to_data_sentinel: D:/Datasets/sentinel
path_to_test_cifar10: D:/Datasets/cifar10/test/
path_to_test_imagenet-mini: D:/Datasets/imagenet-mini/val/
path_to_test_xBD: D:/Datasets/xBD/test/
path_to_train_cifar10: D:/Datasets/cifar10/train/
path_to_train_imagenet-mini: D:/Datasets/imagenet-mini/train/
path_to_train_xBD: D:/Datasets/xBD/train/
predhead_dim: []
prjhead_dim:
- - 512
  - 512
  - BN
  - RELU
- - 512
  - 512
  - BN
  - RELU
- - 512
  - 512
  - BN
  - RELU
- - 512
  - 128
  - BN
  - None
runing time(min): 35.85304206609726
samples: 0
schedule: cos
seed: 1
shuffle: true
stop_gradient: false
transform(min): 6.508
update(min): 11.815666666666667
view: 4
view_model: mean_n
